added new VisIt base images

diff --git a/build/docker/bases/Dockerfile.archlinux.visit b/build/docker/bases/Dockerfile.archlinux.visit
--- a/build/docker/bases/Dockerfile.archlinux.visit
+++ b/build/docker/bases/Dockerfile.archlinux.visit
@@ -1,60 +1,43 @@
 # syntax=docker/dockerfile:1
-
 ##################
-# Author: Josh Bowden
-# Company: Inria
-# Date: 25/01/2022
-#
-# 
-##################
-#
 ## Usage of this file (standalone or automated via gitlab CI): 
-# The gitlab.inria.fr/Damaris/damaris repo should build without the secret setup.
+#
+# This is a base image definition on which to build Damaris
 # 
-# To build the damaris repo (no password needed):
-# export TAG=v1.6.0
-# export VISIT_VER=3.2.1
-# sudo  DOCKER_BUILDKIT=1 docker build --progress=plain -t \
-#            registry.gitlab.inria.fr/damaris/damaris:${TAG}-archlinux-visit${VISIT_VER} \
-#            --build-arg INPUT_damaris_ver=${TAG} \
-#            --build-arg INPUT_repo=damaris \
-#            --build-arg INPUT_visit_ver=${VISIT_VER} \
-#                -f ./Dockerfile.archlinux.visit .
+# Visit builds use a multi-stage build so as to get some information 
+# about the compiler and architecture being used
+# 
+#   ## Build stage 1
+#   DOCKER_IMAGE_BASENAME=registry.gitlab.inria.fr/damaris/damaris-development
+#   DOCKERFILE=archlinux
+#   DOCKER_BUILDKIT=1 docker build --progress=plain\
+#     --target base_builder   \
+#     -t  ${DOCKER_IMAGE_BASENAME}:${TAG} \
+#     --build-arg INPUT_visit_ver=${VISIT_VERSION} \
+#     -f ./Dockerfile.$DOCKERFILE.visit .
 #
-#
-# N.B. MY_CI_READ_REPO_PWD is the filename that contains the token for user 'gitlab-read-repo' 
-# User 'gitlab-read-repo' is created in the 
-# Settings -> Access tokens page
-# and MY_CI_READ_REPO_PWD is a gitlab CI 'file' variable that contains a gitlab token
-# just created and the variable is created in the 
-# Settings -> CI/CD -> Variables page
-#
+#   docker run --rm -it ${DOCKER_IMAGE_BASENAME}:${TAG} cat /home/docker/vist_arch.txt > ./vist_arch.txt
+#   VISTARCH=$(cat ./vist_arch.txt)
+#   echo "VISTARCH: $VISTARCH"
+
+#  ## Build stage 2
+#  DOCKER_BUILDKIT=1 docker build --progress=plain \
+#     --target visit_builder   \
+#     -t  ${DOCKER_IMAGE_BASENAME}:${TAG} \
+#     --build-arg INPUT_visit_ver=${VISIT_VERSION} \
+#     --build-arg  INPUT_os_arch_compiler_ver=$VISTARCH \
+#     -f ./Dockerfile.$DOCKERFILE.visit .
+# 
 ###################
-#
-## To test the created docker image:
-# 1/ Log in to the gitlab repository 
-# N.B. You may need a ~/.docker/config.json file configured with an access token
-# > docker login registry.gitlab.inria.fr
-# 
-# 2/ Use docker run as it does not leave the container running on exit and run Damaris tests:
-#    Map the shared memory filesystem and the Paraview Catalyst port
-# 
-# > docker run --rm -v /dev/shm:/dev/shm -p 22222:22222 -it registry.gitlab.inria.fr/damaris/damaris:<branch>-<OS>-<Paraview_version> /bin/bash
-# <container prompt> ctest
-#
-# > sudo docker run --rm -v /dev/shm:/dev/shm -p 22222:22222 -it registry.gitlab.inria.fr/damaris/damaris:v1.5.0-archlinux-pvv5100 /bin/bash
-# > cd /home/docker/local/examples/storage/
-# > mpirun -np 4 ./3dmesh 3dmesh.xml
-######################################################################################
 
 
 # This is a global arg that can be used in all stages of the build
-
+ARG INPUT_visit_ver
 
 ########################################
 ## Stage 1 of build
 ########################################
-FROM archlinux:base-devel AS builder
+FROM archlinux:base-devel AS base_builder
 SHELL ["/bin/bash", "-c"]
 
 
@@ -139,61 +122,90 @@ COPY --chown=docker:docker *.tgz ${INSTALLTMDIR}/
 COPY --chown=docker:docker build_visit* ${INSTALLTMDIR}/
 
 
-
 ARG INPUT_visit_ver
 ENV VISIT_VERSION=$INPUT_visit_ver
 
 
-RUN VISIT_VER_UNDERSCORE=${VISIT_VERSION//./_} \
+RUN cd /home/docker \
+  && export VISIT_VER_UNDERSCORE=${VISIT_VERSION//./_} \
+  && env -i /bin/bash \
+  && source ${INSTALLTMDIR}/build_visit${VISIT_VER_UNDERSCORE}_to_source \
+  && initialize_build_visit \
+  && echo $VISITARCHTMP > vist_arch.txt 
+
+# Now we need to copy vist_arch.txt  from the container and use its contents as
+# an arg to stage 2 "INPUT_os_arch_compiler_ver"
+  
+
+
+####################################
+## Second stage of build - Build Visit
+####################################
+FROM base_builder AS visit_builder
+SHELL ["/bin/bash", "-c"]
+ 
+
+# GCCVERSION=$(g++ -v 2>&1 | grep "gcc version" | awk '{ print $3 }' | sed 's|\.[^.]*$||')
+ARG INPUT_os_arch_compiler_ver
+ENV VISIT_ARCH=$INPUT_os_arch_compiler_ver
+
+# N.B. Could set: --arch "" as it would remove the "linux-x86_64_gcc-X.Y"
+ENV VISIT_PYTHON3=${INSTALL_PREFIX}/python/3.7.7/${VISIT_ARCH}
+ENV PATH=${VISIT_PYTHON3}/bin:${PATH}
+ENV LD_LIBRARY_PATH=${VISIT_PYTHON3}/lib:${VISIT_PYTHON3}/lib64:${LD_LIBRARY_PATH}
+
+ENV PAR_COMPILER=${MPICC}
+ENV PAR_COMPILER_CXX=${MPICXX}
+ENV HOSTNAME_DOCKER=
+
+# Define INPUT_visit_ver with a default
+ARG INPUT_visit_ver
+ENV VISIT_VERSION=$INPUT_visit_ver
+
+
+
+# This is a multi-stage RUN command that is required as the build_vist script is not so robust.
+# The initial sed is needed to fix how the build_visit script finds Python on Ubuntu 20
+# The first "We will try again 1" is needed as Mesa does not find Python (this may be related to the initial sed commands above?)
+# The second "We will try again 2" is needed as the build_visit script does not run cmake correctly - seems to have issues with quotations of multiple value arguments.
+# The final sed commands swap the gcc versions for the mpicc versions in the cmake config file (even though PAR_COMPILER is set correctly)
+# N.B. Flags can be added to ./build_visit${VISIT_VER_UNDERSCORE} to minimise warnings from LLVM:
+# --cflags "-Wno-class-memaccess -Wno-cast-function-type -fcommon" --cxxflags "-Wno-class-memaccess -Wno-cast-function-type -fcommon"
+# N.B. cxxflag "-fpermissive" needed due to issue in VTK with Python3.7 and passing  char* when const char * is expected.
+#      cflag   "-fcommon" needed for Mesa that fails on gcc >= 10 due to change in default linking
+RUN export VISIT_VER_UNDERSCORE=${VISIT_VERSION//./_} \
     && cd ${INSTALLTMDIR} \
     && mkdir ./third_party \
     && chmod +x build_visit${VISIT_VER_UNDERSCORE} \
     && sed -i 's|error "python library was not found, cannot configure python"|PYTHON_LIBRARY=$(pkg-config --libs python3-embed);  PYTHON_LIBRARY="lib${PYTHON_LIBRARY:2}.so" ; if [ ! -e "${PYTHON_LIBRARY_DIR}/${PYTHON_LIBRARY}" ] ; then  error "python library was not found, cannot configure python" ; fi|g' ./build_visit${VISIT_VER_UNDERSCORE} \
-    && sed -i 's|vopts="${vopts} -DPYTHON_EXTRA_LIBS:STRING=${VTK_PY_LIBS}"|vopts="${vopts} -DPYTHON_EXTRA_LIBS:STRING=\\\"${VTK_PY_LIBS}\\\""|g' ./build_visit${VISIT_VER_UNDERSCORE} 
-
-
-# N.B. cxxflag "-fpermissive" needed due to issue in VTK with Python3.7 and passing  char* when const char * is expected.
-# No Visit, just dependencies
-# This fails during VTK build as python is only available as python3
-RUN VISIT_VER_UNDERSCORE=${VISIT_VERSION//./_} \
+    && sed -i 's|vopts="${vopts} -DPYTHON_EXTRA_LIBS:STRING=${VTK_PY_LIBS}"|vopts="${vopts} -DPYTHON_EXTRA_LIBS:STRING=\\\"${VTK_PY_LIBS}\\\""|g' ./build_visit${VISIT_VER_UNDERSCORE} \
+    && yes yes | ./build_visit${VISIT_VER_UNDERSCORE}  --thirdparty-path ${INSTALL_PREFIX} --mesagl --llvm --server-components-only --stdout  --cc ${GCC}  --cxx ${GPP}   --makeflags -j${NUMCORES} --system-cmake --parallel --cflags "-Wno-class-memaccess -Wno-cast-function-type -fpermissive -fcommon" --cxxflag "-Wno-class-memaccess -Wno-cast-function-type -fpermissive -fcommon" --prefix $INSTALL_PREFIX/visit  \
+    || echo "We will try again 1" \
+    && cd ${VISIT_PYTHON3}/bin \
+    &&  if [[ ! -f ./python ]] ; then ln -s python3 python ; fi \
+    && cd ${INSTALLTMDIR} \  
+    && yes yes | ./build_visit${VISIT_VER_UNDERSCORE} --thirdparty-path ${INSTALL_PREFIX} --mesagl --llvm --server-components-only --stdout  --cc ${GCC}  --cxx ${GPP}  --makeflags -j${NUMCORES} --system-cmake --parallel  --cflags "-Wno-class-memaccess -Wno-cast-function-type -fpermissive -fcommon" --cxxflag "-Wno-class-memaccess -Wno-cast-function-type -fpermissive -fcommon" --prefix $INSTALL_PREFIX/visit  \
+    || echo "We will try again 2"  \   
     && cd ${INSTALLTMDIR} \
-    && export PAR_COMPILER=${MPICC} \
-    && export PAR_COMPILER_CXX=${MPICXX} \
-    && yes yes | ./build_visit${VISIT_VER_UNDERSCORE} --no-visit  --thirdparty-path ${INSTALL_PREFIX} --mesagl --llvm --server-components-only --stdout  --cc ${GCC} --cxx ${GPP}  --cflags "-I${INSTALL_PREFIX}/include -fcommon" --cxxflag "-Wno-class-memaccess -Wno-cast-function-type -fpermissive -fcommon"  --makeflags -j${NUMCORES} --system-cmake --parallel --prefix $INSTALL_PREFIX/visit \
-    || echo "We will try again 1"
+    && ls -la \
+    && rm -fr ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
+    && mkdir -p ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
+    && cd ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
+    && sed -i "s|VISIT_OPTION_DEFAULT(VISIT_C_COMPILER ${GCC}|VISIT_OPTION_DEFAULT(VISIT_C_COMPILER ${MPICC}|g" ${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake \
+    && sed -i "s|VISIT_OPTION_DEFAULT(VISIT_CXX_COMPILER ${GPP}|VISIT_OPTION_DEFAULT(VISIT_CXX_COMPILER ${MPICXX}|g" ${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake \
+    && /usr/bin/cmake -DVISIT_CONFIG_SITE:FILEPATH=${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake -DVISIT_INSTALL_THIRD_PARTY:BOOL=ON -DVISIT_PARALLEL:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DVISIT_C_COMPILER:FILEPATH=${MPICC} -DVISIT_CXX_COMPILER:FILEPATH=${MPICXX}  -DVISIT_C_FLAGS:STRING=" -m64 -fPIC -I${INSTALL_PREFIX}/include" -DVISIT_CXX_FLAGS:STRING=" -m64 -fPIC -I${INSTALL_PREFIX}/include " -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DCPACK_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DCPACK_PACKAGING_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DVISIT_SERVER_COMPONENTS_ONLY:BOOL=ON ../src  \
+    && make -j${NUMCORES} \
+    && touch ./resources/help/en_US/manual \
+    && make install \
+    || echo "We will try again 3" \
+    && rm -fr ${INSTALLTMDIR} 
+    
+ENV PATH=${INSTALL_PREFIX}/visit/bin:${PATH}
 
-
-# gcc --version | grep gcc | awk { print $3 }
-ENV VISIT_PYTHON3=${INSTALL_PREFIX}/python/3.7.7/linux-x86_64_gcc-11.2
-RUN ln -s ${VISIT_PYTHON3}/bin/python3 ${VISIT_PYTHON3}/bin/python
-ENV PATH=${VISIT_PYTHON3}/bin:${PATH}
-ENV LD_LIBRARY_PATH=${VISIT_PYTHON3}/lib:${VISIT_PYTHON3}/lib64:${LD_LIBRARY_PATH}
-
-
-
-# Now finish dependencies and then try to configure VisIt, and fail due to -fPic or some other flag
-# Mesa failed on gcc >= 10 due to change in default linking, need to add -fcommon
-RUN VISIT_VER_UNDERSCORE=${VISIT_VERSION//./_} \
-    && cd ${INSTALLTMDIR} \
-    && export PAR_COMPILER=${MPICC} \
-    && export PAR_COMPILER_CXX=${MPICXX} \
-    && yes yes | ./build_visit${VISIT_VER_UNDERSCORE} --thirdparty-path ${INSTALL_PREFIX} --mesagl --llvm --server-components-only --stdout  --cc ${GCC} --cxx ${GPP}  --cflags "-I${INSTALL_PREFIX}/include -fcommon" --cxxflags "-Wno-class-memaccess -Wno-cast-function-type -fcommon"  --system-cmake --parallel --makeflags -j${NUMCORES}  --prefix $INSTALL_PREFIX/visit \
-    || echo "We will try again 2c"
-
-ENV HOSTNAME_DOCKER=
-# ENV HOSTNAME_DOCKER=buildkitsandbox
-
-RUN rm -fr ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
-  && mkdir -p ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
-  && cd ${INSTALLTMDIR}/visit${VISIT_VERSION}/build \
-  && sed -i "s|VISIT_OPTION_DEFAULT(VISIT_C_COMPILER ${GCC}|VISIT_OPTION_DEFAULT(VISIT_C_COMPILER ${MPICC}|g" ${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake \
-  && sed -i "s|VISIT_OPTION_DEFAULT(VISIT_CXX_COMPILER ${GPP}|VISIT_OPTION_DEFAULT(VISIT_CXX_COMPILER ${MPICXX}|g" ${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake \
-  && /usr/bin/cmake -DVISIT_CONFIG_SITE:FILEPATH=${INSTALLTMDIR}/$HOSTNAME_DOCKER.cmake -DVISIT_INSTALL_THIRD_PARTY:BOOL=ON -DVISIT_PARALLEL:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DVISIT_C_COMPILER:FILEPATH=${MPICC} -DVISIT_CXX_COMPILER:FILEPATH=${MPICXX} -DVISIT_C_FLAGS:STRING=" -m64 -fPIC -I${INSTALL_PREFIX}/mesagl/17.3.9/linux-x86_64_gcc-11.2/include" -DVISIT_CXX_FLAGS:STRING=" -m64 -fPIC -I${INSTALL_PREFIX}/mesagl/17.3.9/linux-x86_64_gcc-11.2/include -Wno-class-memaccess -Wno-cast-function-type" -DCMAKE_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DCPACK_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DCPACK_PACKAGING_INSTALL_PREFIX:PATH=${INSTALL_PREFIX}/visit -DVISIT_SERVER_COMPONENTS_ONLY:BOOL=ON ../src  \
-  && make -j${NUMCORES} \
-  && touch ./resources/help/en_US/manual \
-  && make install
-
-
+RUN visit -env -engine > ~/tmp.txt \
+   && sed -i 's|^|export |g' ~/tmp.txt \
+   && sed -i 's|^export LD_LIBRARY_PATH.*|&$LD_LIBRARY_PATH|' ~/tmp.txt  \
+   && cat ~/tmp.txt >> ~/.bashrc
 
  
 CMD ["/bin/bash"]
diff --git a/build/docker/damaris/Dockerfile._BASEWITHPARAVIEW_.visit b/build/docker/damaris/Dockerfile._BASEWITHPARAVIEW_.visit
--- a/build/docker/damaris/Dockerfile._BASEWITHPARAVIEW_.visit
+++ b/build/docker/damaris/Dockerfile._BASEWITHPARAVIEW_.visit
@@ -25,9 +25,13 @@ ENV SHLIBS_ON_OFF=ON
 # Build examples
 ENV EXAMPLES_ON_OFF=ON
 
+# Set this incase it changes in the base images
+ENV VISIT_PYTHON_VERSION=3.7
+
 # N.B INPUT_damaris_ver to be provided on the docker build -t registry.gitlab.inria.fr/damaris-development:${TAG}  --build-arg INPUT_damaris_ver=v1.5.0 --build-arg INPUT_repo="damaris-development" -f Dockerfile.ubuntu20 .
 ARG INPUT_damaris_ver
 ARG INPUT_repo
+
 # ARG INPUT_repo  # making this a global arge and defining before stage 1
 ENV DAMARIS_VERSION=$INPUT_damaris_ver
 ENV repo=$INPUT_repo
@@ -38,14 +42,15 @@ ENV LD_LIBRARY_PATH=_MPI_BIN_PATH_../_DISTLIB_:${LD_LIBRARY_PATH}
 
 
 
-
-RUN if [[ "$INSTALLTMDIR" == "" ] ;   then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: INSTALLTMDIR" ;   exit 1; fi
-RUN if [[ "$INSTALL_PREFIX" == "" ] ; then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: INSTALL_PREFIX" ; exit 1; fi
-RUN if [[ "$VISIT_VERSION" == "" ] ;  then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: VISIT_VERSION" ;  exit 1; fi
-RUN if [[ "$MPICXX" == "" ] ;         then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPICXX" ;         exit 1; fi
-RUN if [[ "$MPICC" == "" ] ;          then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPICC" ;          exit 1; fi
-RUN if [[ "$MPIFORT" == "" ] ;        then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPIFORT" ;        exit 1; fi
-
+RUN if [[ "$INSTALLTMDIR" == "" ] ;   then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: INSTALLTMDIR" ;   exit 1; fi  \
+ && if [[ "$INSTALL_PREFIX" == "" ] ; then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: INSTALL_PREFIX" ; exit 1; fi  \
+ && if [[ "$VISIT_VERSION" == "" ] ;  then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: VISIT_VERSION" ;  exit 1; fi  \
+ && if [[ "$MPICXX" == "" ] ;         then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPICXX" ;         exit 1; fi  \
+ && if [[ "$MPICC" == "" ] ;          then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPICC" ;          exit 1; fi  \
+ && if [[ "$MPIFORT" == "" ] ;        then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: MPIFORT" ;        exit 1; fi  \
+ && if [[ "$VISIT_PYTHON3" == "" ] ;  then echo "ERROR: VAR DOES NOT EXIST IN BASE IMAGE: VISIT_PYTHON3" ;  exit 1; fi  
+ 
+ 
 _INSTALL_GFORT_
 
 # may need this:  -DParaView_DIR=$CATALYSTDIR
@@ -81,7 +86,7 @@ RUN --mount=type=secret,id=thepassword if [ "$repo" == "damaris-development" ] ;
   && chown -R docker:docker /home/docker
 
 USER docker
-# ENV PYTHONPATH=/usr/local/lib/python3.8/site-packages/_paraview.zip:/usr/local/lib/python3.8/site-packages/_vtk.zip:/usr/local/lib/python3.8/site-packages:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages
+ENV PYTHONPATH=$VISIT_PYTHON3/lib/python$VISIT_PYTHON_VERSION/:VISIT_PYTHON3/lib/python$VISIT_PYTHON_VERSION/site-packages:$VISIT_PYTHON3/lib/python$VISIT_PYTHON_VERSION/lib-dynload:$PYTHONPATH
 # ENV LD_LIBRARY_PATH=_MPI_BIN_PATH_../_DISTLIB_:${LD_LIBRARY_PATH}
 
 WORKDIR ${INSTALL_PREFIX}/examples
